main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

story7/urls.py
from django.urls import path

from . import views

app_name = 'story7'

urlpatterns = [
    path('', views.homepage, name='homepage'),
]

story8/urls.py
from django.urls import path

from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.homepage8, name='homepage8'),
    path('data', views.fungsi_data, name='data'),


]

story9/urls.py
from django.urls import path

from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.logout_page, name='logout'),
    path('login/', views.login_page, name='login'),
    path('register/', views.register_page, name='register'),





]

storybagian2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls',namespace="main")),
    path('story7/',include('story7.urls', namespace="story7")),
    path('story8/',include('story8.urls', namespace="story8")),
    path('story9/',include('story9.urls', namespace="story9")),


]

main/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Login(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

story9/forms.py
from django import forms
from .models import Login
from django.contrib.auth import get_user_model

User = get_user_model()

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control text-center'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control text-center'}))

class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control text-center'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control text-center'}))
    password_first = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control text-center'}))
    password_again = forms.CharField(label="Confirm password", widget=forms.PasswordInput(attrs={'class': 'form-control text-center'}))


    def clean(self):
        cleaned_data = self.cleaned_data
        password_one = self.cleaned_data.get('password_first')
        password_two = self.cleaned_data.get('password_again')
        if password_one != password_two:
            raise forms.ValidationError("Passwords don't match")
        return cleaned_data

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("The username you've chosen is unavailable.")
        return username

    def clean_email(self):
        email_address = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email_address)
        if qs.exists():
            raise forms.ValidationError("The email address you've chosen is already registered.")
        return email_address

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

story7/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request, 'homepage.html')

story8/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import JsonResponse
import requests
import json

# Create your views here.

def homepage8(request):
    response = {}
    return render(request, 'homepage8.html',response)

def fungsi_data(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET['q']
    ret = requests.get(url)
    data = json.loads(ret.content)
    return JsonResponse(data, safe=False)

story9/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from .models import Login
from .forms import LoginForm, RegisterForm
 
User = get_user_model()

def login_page(request):
    form = LoginForm(request.POST or None)
    context = {
        'form': form
    }
    print(request.user.is_authenticated)
    if form.is_valid():
        print(form.cleaned_data)
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            print("error.......")

    return render(request, 'login.html', context=context)

def register_page(request):
    form = RegisterForm(request.POST or None)
    context = {
        'form': form,
    }
    if form.is_valid():
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password_first")
        User.objects.create_user(username, email, password)
        messages.success(request, f'Account {username} has been created. Please Log In!')
        return redirect('/story9/login')
        
    return render(request,'register.html', context=context)

def logout_page(request):
    logout(request)
    return render(request, "main/home.html")

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>
{% endblock meta %}

{% block content %}
<div class="container main">
  {% if user.is_authenticated %}
  <h1 style="color: #ecb390;"><strong>Hello,{{user.username}}!</strong></h1>
  {% else %}
  <h1><strong>Hello!</strong></h1>
  {% endif %}

  <h1>Welcome to Azzahra's website,</h1>
  <h1>Please select a story you want to see</h1>
  <a href="{% url 'story7:homepage' %}">
    <button class="button">Story 7</button>
  </a>
  <a href="{% url 'story8:homepage8' %}">
    <button class="button">Story 8</button>
  </a>
</div>
{% endblock content %}

story7/templates/homepage.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Home</title>

<script src="{% static 'js/story7.js' %}"></script>
{% endblock meta %}

{% block content %}
<div class="d-flex justify-content-center">
<h1 class="text">
    About Me
</h1>
</div>
<div class="container a">
<div id="accordionProfile">
  <h3>Profile
    <span style="float: right;">
        <button style="font-size: 15px;" class="button-up"><i class="fas fa-angle-up"></i></button>
        <button style="font-size: 15px;" class="button-down"><i class="fas fa-angle-down"></i></button>
    </span>
  </h3>
  <div>
      <p>Hello, my name is Azzahra Banowati Rahmah. I'm an experience seeker who is constantly learning how to be a better person
          for my surrounding. Currently studying as an Information System Student in University on Indonesia.
      </p>
  </div>
</div>
<div id="accordionActivities">
  <h3>Activities
    <span style="float: right;">
        <button style="font-size: 15px;" class="button-up"><i class="fas fa-angle-up"></i></button>
        <button style="font-size: 15px;" class="button-down"><i class="fas fa-angle-down"></i></button>
    </span>
  </h3>
  <div>
    <ul>
        <li>Kuliah</li>
        <li>Kepanitiaan</li>
        <li>Berkhayal</li>
    </ul>
  </div>
</div>
<div id="accordionExperiences">
  <h3>Experiences
    <span style="float: right;">
        <button style="font-size: 15px;" class="button-up"><i class="fas fa-angle-up"></i></button>
        <button style="font-size: 15px;" class="button-down"><i class="fas fa-angle-down"></i></button>
    </span>
  </h3>
  <div>
    <ul>
        <li>Staff of Fundraising - Compfest 2020</li>
        <li>Treasurer - PMB 2020</li>
        <li>Staff of Relation - Wisuda Genap 2020</li>
    </ul>
  </div>
</div>
<div id="accordionAchievements">
  <h3>Achievements
    <span style="float: right;">
        <button style="font-size: 15px;" class="button-up"><i class="fas fa-angle-up"></i></button>
        <button style="font-size: 15px;" class="button-down"><i class="fas fa-angle-down"></i></button>
    </span>
  </h3>
  <div>
      <p>Jadi orang baik yang sukses. Please aamiin-in</p>
  </div> 
</div>
</div>
</div>
 
{% endblock content %}

story8/templates/homepage8.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Homepage</title>
<script src="{% static 'story8.js' %}"></script>
{% endblock meta %}

{% block content %}

<div class="container justify-content-center text-center p-5" style="max-width: 700px;">
    <h3 style="margin-top: 50px;font-family: 'Manuale', serif;font-size: 50px;"><strong>Search Something to Read</strong></h3>
    <input id="keyword"  style ="margin-top: 40px;" placeholder="Input the book name">
</div>





<div class="container table">
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Cover</th>
            <th scope="col">Title</th>
            <th scope="col">Author</th>
            
        </tr>
    </thead>
    <tbody id="listBuku"></tbody>
    <!-- <tbody id="daftar_isi"></tbody> -->
</table>
</div>


{% endblock content %}

story9/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="container justify-content-center text-center p-5" style="margin-top: 100px;">
    <h1 style="font-family: 'Manuale', serif;font-size: 50px">Log In</h1>
    <div class="row m-5 justify-content-center">
    <div class="col-md-8 col-sm-8">
        <form method="POST">

            {% csrf_token %}
            {{ form.as_p }}
        
            <button type="submit" class="btn btn-primary" style="background-color:#ecb390; border-color: #ecb390;">Login</button>
        
        </form>
    </div>
</div>
<div class="row m-5 justify-content-center">
    <div class="col-md-8 col-sm-8">
        <h5 style="color: black;">Don't have an account? <a href="{% url 'story9:register'%}">Sign up</a></h5>
    </div>        
</div>
</div>




{% endblock content %}

story9/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Sign In</title>
{% endblock meta %}

{% block content %}
<div class="container justify-content-center text-center p-5" style="margin-top: 50px;">
<div class="row m-5 justify-content-center">
    <div class="col text-center">
        <h1 style="font-family: 'Manuale', serif;font-size: 50px">Create a new account</h1>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <h5 style="color: black;" {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </h5>
            {% endfor %}
        </ul>
        {% endif %}     
    </div>
</div>
<div class="row m-5 justify-content-center">
    <div class="col-md-8 col-sm-8">
        <form method="POST">

            {% csrf_token %}
        
            {{ form.as_p }}
        
            <button type="submit" class="btn btn-primary" style="background-color:#ecb390; border-color: #ecb390;">Register</button>
        
        </form>
    </div>        
</div>
<div class="row m-5 justify-content-center">
    <div class="col-md-8 col-sm-8">
        <h5 style="color: black;">Already have an account? <a href="{% url 'story9:login'%}">Log in</a></h5>
    </div>   
</div>


</div>


{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
  <link rel="stylesheet" href="{% static 'js/jquery-3.5.1.js' %}">


  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <a class="navbar-brand" style="font-weight: 700; font-size:xx-large;" href="{% url 'main:home' %}#">ABR.</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" href="{% url 'main:home' %}">Home</a>
        <a class="nav-link" href="{% url 'story7:homepage' %}">Story 7</a>
        <a class="nav-link" href="{% url 'story8:homepage8' %}">Story 8</a>
      </div>

        <div class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <h2>Welcome {{user.username}}!</h2>
        </a>
        <a class="nav-link" href="{% url 'story9:logout'%}">
          <h5><strong>Log Out</strong></h5>
        </a>

        {% else %}
          <a class="nav-link" href="{% url 'story9:login'%}">
            <h5><strong>Log In</strong></h5>
          </a>
          <a class="nav-link" href="{% url 'story9:register'%}">
            <h5><strong>Sign Up</strong></h5>
          </a>
        {% endif %}
        </div>



    </div>
  </nav>
  {% block content %}
  
  {% endblock content %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
</body>

</html>